plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
packageExtensions:
  "debug@*":
    peerDependenciesMeta:
      "supports-color":
        optional: true
