version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=$SETTINGS_MODULE
    volumes:
      - .:/keeper
    ports:
      - "8000:8000"
    env_file:
      # podman-compose currently does not work with any other env_file names
      - .env
    depends_on:
      - db
  db:
    image: postgres:15.4
    volumes:
      - ./postgres_data:/var/lib/pg_data
    env_file:
      # podman-compose currently does not work with any other env_file names
      - .env
    environment:
      POSTGRES_DB: $DATABASES_NAME
      POSTGRES_USER: $DATABASES_USER
      POSTGRES_PASSWORD: $DATABASES_PASSWORD
#    user: $POSTGRES_UID:$POSTGRES_GID

volumes:
  postgres_data:
