# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-13 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0002_auto_20180507_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='accession_status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('REV', 'Under Review'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='NEW', max_length=5),
        ),
        migrations.AlterField(
            model_name='accession',
            name='affiliation',
            field=models.CharField(choices=[('STU', 'Student'), ('FAC', 'Faculty'), ('STA', 'Staff'), ('ALU', 'Alumni'), ('OTH', 'Other')], max_length=5),
        ),
    ]
