# Generated by Django 4.0.4 on 2022-05-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0003_auto_20220113_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='accession_status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('REV', 'Under Review'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='NEW', max_length=25),
        ),
        migrations.AlterField(
            model_name='accession',
            name='affiliation',
            field=models.CharField(choices=[('STU', 'Student'), ('FAC', 'Faculty'), ('STA', 'Staff'), ('ALU', 'Alumni'), ('OTH', 'Other')], max_length=25),
        ),
    ]
