# Generated by Django 4.2.4 on 2023-08-25 20:43

from django.db import migrations
import keeper.models
import keeper.validators
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0004_alter_accession_accession_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=keeper.models.file_upload_location, validators=[keeper.validators.validate_file_type, keeper.validators.validate_file_size]),
        ),
    ]
